// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/wasm/v2/wasm.proto

package envoy_config_wasm_v2

import (
	fmt "fmt"
	core "github.com/cilium/proxy/go/envoy/api/v2/core"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Configuration for a Wasm VM.
// [#next-free-field: 6]
type VmConfig struct {
	// A unique ID for a VM permitting multiple filters/services can share the same VM.
	// If left blank the 'vm_id' will be a hash of the Wasm code enabling the VM to persist over
	// reconfigurations if the code does not change. This will also result in filters/services running
	// the same Wasm code sharing the same VM. If set, 'vm_id' should include a version number
	// otherwise the VM will not be reloaded if the Wasm code changes.
	VmId string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	// The Wasm runtime type (see source/extensions/commmon/wasm/well_known_names.h).
	Runtime string `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// The Wasm code that Envoy will execute.
	Code *core.DataSource `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// The Wasm configuration string used on initialization of a new VM (proxy_onStart).
	Configuration string `protobuf:"bytes,4,opt,name=configuration,proto3" json:"configuration,omitempty"`
	// Allow the wasm file to include pre-compiled code on VMs which support it.
	AllowPrecompiled     bool     `protobuf:"varint,5,opt,name=allow_precompiled,json=allowPrecompiled,proto3" json:"allow_precompiled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VmConfig) Reset()         { *m = VmConfig{} }
func (m *VmConfig) String() string { return proto.CompactTextString(m) }
func (*VmConfig) ProtoMessage()    {}
func (*VmConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f222ab516220f4d, []int{0}
}

func (m *VmConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VmConfig.Unmarshal(m, b)
}
func (m *VmConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VmConfig.Marshal(b, m, deterministic)
}
func (m *VmConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VmConfig.Merge(m, src)
}
func (m *VmConfig) XXX_Size() int {
	return xxx_messageInfo_VmConfig.Size(m)
}
func (m *VmConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_VmConfig.DiscardUnknown(m)
}

var xxx_messageInfo_VmConfig proto.InternalMessageInfo

func (m *VmConfig) GetVmId() string {
	if m != nil {
		return m.VmId
	}
	return ""
}

func (m *VmConfig) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *VmConfig) GetCode() *core.DataSource {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *VmConfig) GetConfiguration() string {
	if m != nil {
		return m.Configuration
	}
	return ""
}

func (m *VmConfig) GetAllowPrecompiled() bool {
	if m != nil {
		return m.AllowPrecompiled
	}
	return false
}

// Base Configuration for Wasm Plugins e.g. fiters and services.
type PluginConfig struct {
	// A unique name for a filters/services in a VM for use in identifiying the filter/service if
	// multiple filters/services are handled by the same vm_id and root_id and for logging/debugging.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A unique ID for a set of filters/services in a VM which will share a RootContext and Contexts
	// if applicable (e.g. an Wasm HttpFilter and an Wasm AccessLog). If left blank, all
	// filters/services with a blank root_id with the same vm_id will share Context(s).
	RootId string `protobuf:"bytes,2,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	// Configuration for finding or starting VM.
	VmConfig *VmConfig `protobuf:"bytes,3,opt,name=vm_config,json=vmConfig,proto3" json:"vm_config,omitempty"`
	// Filter/service configuration string e.g. a serialized protobuf which will be the
	// argument to the proxy_onConfigure() call.
	Configuration        string   `protobuf:"bytes,4,opt,name=configuration,proto3" json:"configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginConfig) Reset()         { *m = PluginConfig{} }
func (m *PluginConfig) String() string { return proto.CompactTextString(m) }
func (*PluginConfig) ProtoMessage()    {}
func (*PluginConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f222ab516220f4d, []int{1}
}

func (m *PluginConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginConfig.Unmarshal(m, b)
}
func (m *PluginConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginConfig.Marshal(b, m, deterministic)
}
func (m *PluginConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginConfig.Merge(m, src)
}
func (m *PluginConfig) XXX_Size() int {
	return xxx_messageInfo_PluginConfig.Size(m)
}
func (m *PluginConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PluginConfig proto.InternalMessageInfo

func (m *PluginConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PluginConfig) GetRootId() string {
	if m != nil {
		return m.RootId
	}
	return ""
}

func (m *PluginConfig) GetVmConfig() *VmConfig {
	if m != nil {
		return m.VmConfig
	}
	return nil
}

func (m *PluginConfig) GetConfiguration() string {
	if m != nil {
		return m.Configuration
	}
	return ""
}

// WasmService is configured as a built-in *envoy.wasm_service* :ref:`ServiceConig
// <envoy_api_msg_config.wasm.v2.ServiceConfig>`. This opaque configuration will be used to
// create a Wasm Service.
type WasmService struct {
	// General plugin configuration.
	Config *PluginConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// If true, create a single VM rather than creating one VM per silo. Such a singleton can
	// not be used with filters.
	Singleton bool `protobuf:"varint,2,opt,name=singleton,proto3" json:"singleton,omitempty"`
	// If set add 'stat_prefix' as a prefix to all stats.
	StatPrefix           string   `protobuf:"bytes,3,opt,name=stat_prefix,json=statPrefix,proto3" json:"stat_prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WasmService) Reset()         { *m = WasmService{} }
func (m *WasmService) String() string { return proto.CompactTextString(m) }
func (*WasmService) ProtoMessage()    {}
func (*WasmService) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f222ab516220f4d, []int{2}
}

func (m *WasmService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasmService.Unmarshal(m, b)
}
func (m *WasmService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasmService.Marshal(b, m, deterministic)
}
func (m *WasmService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmService.Merge(m, src)
}
func (m *WasmService) XXX_Size() int {
	return xxx_messageInfo_WasmService.Size(m)
}
func (m *WasmService) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmService.DiscardUnknown(m)
}

var xxx_messageInfo_WasmService proto.InternalMessageInfo

func (m *WasmService) GetConfig() *PluginConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *WasmService) GetSingleton() bool {
	if m != nil {
		return m.Singleton
	}
	return false
}

func (m *WasmService) GetStatPrefix() string {
	if m != nil {
		return m.StatPrefix
	}
	return ""
}

func init() {
	proto.RegisterType((*VmConfig)(nil), "envoy.config.wasm.v2.VmConfig")
	proto.RegisterType((*PluginConfig)(nil), "envoy.config.wasm.v2.PluginConfig")
	proto.RegisterType((*WasmService)(nil), "envoy.config.wasm.v2.WasmService")
}

func init() { proto.RegisterFile("envoy/config/wasm/v2/wasm.proto", fileDescriptor_6f222ab516220f4d) }

var fileDescriptor_6f222ab516220f4d = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x8a, 0xdb, 0x30,
	0x10, 0x86, 0x51, 0xeb, 0xcd, 0xda, 0x93, 0x16, 0x5a, 0xb5, 0xb0, 0x66, 0xd9, 0x76, 0x83, 0xe9,
	0x21, 0x50, 0x90, 0x59, 0xf7, 0xd6, 0xde, 0xd2, 0x5e, 0x72, 0x33, 0x0e, 0xb4, 0xc7, 0xa0, 0xd8,
	0x4a, 0x10, 0x58, 0x92, 0x91, 0x65, 0x25, 0x79, 0x83, 0x3e, 0x45, 0x5f, 0xa5, 0xaf, 0x56, 0x24,
	0xd9, 0xa4, 0x85, 0x1c, 0x7a, 0x92, 0xf4, 0xcf, 0x8c, 0xfe, 0xf9, 0x86, 0x81, 0x47, 0x26, 0xad,
	0x3a, 0xe7, 0xb5, 0x92, 0x7b, 0x7e, 0xc8, 0x8f, 0xb4, 0x17, 0xb9, 0x2d, 0xfc, 0x49, 0x3a, 0xad,
	0x8c, 0xc2, 0x6f, 0x7d, 0x02, 0x09, 0x09, 0xc4, 0x07, 0x6c, 0x71, 0xff, 0x10, 0xca, 0x68, 0xc7,
	0x5d, 0x7a, 0xad, 0x34, 0xcb, 0x77, 0xb4, 0x67, 0xa1, 0xe6, 0xfe, 0xce, 0xd2, 0x96, 0x37, 0xd4,
	0xb0, 0x7c, 0xba, 0x84, 0x40, 0xf6, 0x1b, 0x41, 0xfc, 0x5d, 0x7c, 0xf5, 0x7f, 0xe1, 0x37, 0x70,
	0x63, 0xc5, 0x96, 0x37, 0x29, 0x5a, 0xa0, 0x65, 0x52, 0x45, 0x56, 0xac, 0x1b, 0x9c, 0xc2, 0xad,
	0x1e, 0xa4, 0xe1, 0x82, 0xa5, 0xcf, 0xbc, 0x3c, 0x3d, 0xf1, 0x13, 0x44, 0xb5, 0x6a, 0x58, 0xfa,
	0x7c, 0x81, 0x96, 0xf3, 0xe2, 0x1d, 0x09, 0x7d, 0xd1, 0x8e, 0x13, 0x5b, 0x10, 0xd7, 0x01, 0xf9,
	0x46, 0x0d, 0xdd, 0xa8, 0x41, 0xd7, 0xac, 0xf2, 0xa9, 0xf8, 0x03, 0xbc, 0x0c, 0x7d, 0x0f, 0x9a,
	0x1a, 0xae, 0x64, 0x1a, 0xf9, 0x2f, 0xff, 0x15, 0xf1, 0x47, 0x78, 0x4d, 0xdb, 0x56, 0x1d, 0xb7,
	0x9d, 0x66, 0xb5, 0x12, 0x1d, 0x6f, 0x59, 0x93, 0xde, 0x2c, 0xd0, 0x32, 0xae, 0x5e, 0xf9, 0x40,
	0x79, 0xd1, 0xb3, 0x5f, 0x08, 0x5e, 0x94, 0xed, 0x70, 0xe0, 0x72, 0xa4, 0xc0, 0x10, 0x49, 0x2a,
	0xd8, 0x04, 0xe1, 0xee, 0xf8, 0x0e, 0x6e, 0xb5, 0x52, 0xc6, 0xb1, 0x05, 0x88, 0x99, 0x7b, 0xae,
	0x1b, 0xfc, 0x05, 0x12, 0x2b, 0xb6, 0xc1, 0x7e, 0x04, 0x79, 0x4f, 0xae, 0x0d, 0x98, 0x4c, 0x53,
	0xaa, 0x62, 0x3b, 0xcd, 0xeb, 0xbf, 0x68, 0xb2, 0x9f, 0x08, 0xe6, 0x3f, 0x68, 0x2f, 0x36, 0x4c,
	0x5b, 0x5e, 0x33, 0xfc, 0x19, 0x66, 0xa3, 0x1f, 0xf2, 0x7e, 0xd9, 0x75, 0xbf, 0xbf, 0x99, 0xaa,
	0xb1, 0x02, 0x3f, 0x40, 0xd2, 0x73, 0x79, 0x68, 0x99, 0x51, 0xd2, 0x93, 0xc4, 0xd5, 0x45, 0xc0,
	0x8f, 0x30, 0xef, 0x0d, 0x35, 0x6e, 0x6c, 0x7b, 0x7e, 0xf2, 0x38, 0x49, 0x05, 0x4e, 0x2a, 0xbd,
	0xb2, 0x7a, 0x82, 0x8c, 0xab, 0x60, 0xd7, 0x69, 0x75, 0x3a, 0x5f, 0x75, 0x5e, 0x25, 0xae, 0xdb,
	0xd2, 0xad, 0x47, 0x89, 0x76, 0x33, 0xbf, 0x27, 0x9f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x42,
	0x2b, 0xad, 0x86, 0x97, 0x02, 0x00, 0x00,
}
